### PR TITLE
Wolfram 2nd try

### PR DESCRIPTION
**Pull request by tbeu**
This combines the library update, the license issue ans the Resources issues mentioned in #3 and hopefully should work.

### CODE REVIEW

**Comment by sjoelund** [comment]
Not everything seems to have been merged. For example, all of the images in the Wolfram branch are larger than the ones in the OpenModelica branch.

**Comment by tbeu** [comment]
I do see that Wolfram image Activation.png is larger in file size than original OM image. I did not touch the images. Are they not part of the PR?

**Comment by sjoelund** [comment]
Yes, maltelenz fork contains the changes to images (reverting to what they were before the fixes)

**Comment by tbeu** [comment]
Sorry, I do not see and cannot judge what is right or wrong here. PR contains maltelenz fork (= library update),  your Mozilla lic changes and my correction on Resources dir.

**Comment by tbeu** [comment]
Any ideas how to progress here?

**Comment by tbeu** [comment]
@maltelenz @sjoelund @dietmarw Anyone interested to get Wolfram's and OM's BioChem synchronized again?

**Comment by dietmarw** [comment]
Sorry, but as long as Wolfram is not really willing to include changes already done upstream with their changes I'm not wasting my time here.

**Comment by tbeu** [comment]
I already put quite some time in this PR. @maltelenz Can you please investigate this PR and work on the comments mentioned here and in #3.

**Comment by maltelenz** [comment]
Unfortunately we (Wolfram) don't have the resources to spend further time doing more detailed integration work on this.

**Comment by tbeu** [comment]
That is really sad news. :worried:

**Comment by tbeu** [comment]
Give up.

**Pull request closed without merging**
