### PR TITLE
Wolfram

### PR DESCRIPTION
**Pull request by maltelenz**
Update to version 1.2 from Wolfram MathCore.

### CODE REVIEW

**Comment by dietmarw** [comment]
There are some broken and also unsuitable links in this pull request. For example you link the Modelica 1.1 license to http://www.mathcore.com/products/mathmodelica/libraries/modelicalicense.php which is a dead end and should be actually be pointing to https://modelica.org/licenses/ModelicaLicense1.1

There is actually a conflict here. The Original BioChem here is listed as Modelica 2 license but your code is under 1.1. So this needs to be resolved aswell.

**Comment by dietmarw** [comment]
One more thing. The pull request puts non-modelica files outside the `Resources/` folder which violates the Modelica convention of Modelica libraries. This has already been fixed here. So your fork needs be be adapted before it can be merged.

**Comment by dietmarw** [comment]
A way to resolve this is that you **first** need to *rebase* the Wolfram fork on the latest version from this repo. That way you get all your changes based on the updates here. There will probably be some conflicts that need to be resolved first and then it can be merged back.

**Comment by tbeu** [comment]
This PR is superseded by #4 and can be closed.

**Pull request closed without merging**
